config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  resources :contents
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
    belongs_to :user

    validates :title, :description, presence: true

    has_many :tag_contents, dependent: :destroy
    has_many :tags, through: :tag_contents
end
  

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: {scope: :user_id}

  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tags
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_content, only: [:show, :edit, :update, :destroy]

    def index
        @contents = current_user.contents

        tag_names = params[:tag]
        if tag_names.present?
            @contents = @contents.joins(:tags).where(tags: { name: tag_names }).distinct
        end
    end

    def show
    end

    def new
        @content = Content.new
    end

    def create
        @content = current_user.contents.build(content_params)
        if @content.save
            tags = tags_params.map do |tag_name|
                current_user.tags.where(name: tag_name).first_or_initialize
            end
            @content.tags = tags
            redirect_to contents_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @content.update(content_params)
            tags = tags_params.map do |tag_name|
                current_user.tags.where(name: tag_name).first_or_initialize
            end
            @content.tags = tags
            redirect_to contents_path
        else
            render :edit
        end
    end
    
    def destroy
        @content.destroy

        redirect_to contents_path
    end

    private

    def set_content
        @content = Content.find(params[:id])
    end

    def tags_params
        params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
    end

    def content_params
        params.require(:content).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags_data = current_user.contents.joins(:tags).group('tags.name').count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
    <% content.errors.full_messages.each do |error| %>
        <div class="alert alert-danger" role="alert">
            <%= error %>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div class="field">
        <%= form.label :tags %>
        <%= form.select :tags, options_for_select(current_user.tags.pluck(:name), content.tags.pluck(:name)), {}, { class: 'select2 form-control', multiple: 'multiple' } %>
    </div>
    <div class="submit">
        <%= form.submit %>
    </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<%= form_tag(contents_path, method: :get  ) do %>
    <div class="field">
    <%= label_tag :tags %>
    <%= select_tag 'tag[]', options_for_select(current_user.tags.pluck(:name), params[:tag]), class: 'select2 form-control', multiple: 'multiple'  %>
    </div>
    <div class="submit">
        <%= submit_tag('Search') %>
    </div>
<% end %>


<ul>
    <% @contents.each do |content| %>
        <li><%= content.title %></li>
        <p>Tags: <%= content.tags.pluck(:name).join(', ') %></p>
        <%= link_to "Abrir", content_path(content), class: "btn btn-primary" %>  
        <%= link_to "Editar", edit_content_path(content) , class: "btn btn-secondary" %>   
        <%= link_to "Destroy", content_path(content),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-danger"
                  %> 
    <% end %>
    <br>
    <%= link_to 'New Content', new_content_path, class: "btn btn-success" %>
</ul>

app/views/contents/new.html.erb
<h1>New Content</h1>
<%= render "form", content: @content %>

app/views/contents/show.html.erb
<h1><%= @content.title %></h1>

<p>
    <%= @content.description %>
</p>

app/views/home/index.html.erb
<% @tags_data.each do |tag_name, count| %>
    <% font_size = count * 3 %>

    <span style="font-size:<%=font_size > 10 ? 10 : font_size %>vh">
        <%= link_to tag_name, contents_path(tag: [tag_name]), class: "link-dark" %>
    </span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Home", root_path, class: "nav-item nav-link" %>
          <%= link_to "Conteudos", contents_path, class: "nav-item nav-link" %>
          <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
          <% end %>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>